"""
Django settings for heibanke project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@kvox^h+!9df+j=59cmp&7**(#xbskp!27ts&d*c+(t0^m1pzv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_comments',
    'accounts',
    'jizhang',
    'lesson',
    'mptt',
    'tagging',
    'zinnia',     
    'zinnia_bootstrap',#zinnia_foundation,zinnia_bootstrap
    'zinnia_wymeditor',#zinnia_wymeditor,zinnia_ckeditor
    'captcha',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'heibanke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "./templates"),],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'zinnia.context_processors.version',
            ],
            'loaders':  (
                'app_namespace.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader',
            ),
        },
    },
]

WSGI_APPLICATION = 'heibanke.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# in settings_local.py

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = 'zh-hans'   #'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')

STATICFILES_DIRS = (   
    ("libs",os.path.join(STATIC_ROOT,"libs").replace('\\','/')),  
    ("admin",os.path.join(STATIC_ROOT,"admin").replace('\\','/')),
    ("zinnia",os.path.join(STATIC_ROOT,"zinnia").replace('\\','/')), 
    ("zinnia_bootstrap",os.path.join(STATIC_ROOT,"zinnia_bootstrap").replace('\\','/')), 
    ("zinnia_wymeditor",os.path.join(STATIC_ROOT,"zinnia_wymeditor").replace('\\','/')), 
)

LOGIN_REDIRECT_URL = '/accounts/'


CACHES = {
    'default':{
        'BACKEND':'django.core.cache.backends.locmem.LocMemCache',
    },
    'comparison':{
        'BACKEND':'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'comparison',
        'TIMEOUT': None,
    }
}


ZINNIA_MARKUP_LANGUAGE='markdown'  #markdown or restructuredtext


from settings_local import *
